# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cú na Gramadaí
email: cugram@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Seo suíomh ar a mbeidh gnéithe suimiúla den ghramadach á
  bpé. Táthar ag súil gur earra úsáideach a bheas ann do
  lucht foghlama agus do na cúnna gramadaí uilig - iadsin ar
  ábhar mór sásaimh daoibh an tseilg ghramadaí.  Déanfar
  iarracht súil úr a oibriú ar an ghramadach, ach san am
  chéanna cuidiú a fháil don tsúil úr ó na seanfhoinsí
  eolais is fearr.
baseurl: "cu_gram" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: curb
github_username:  pmcu
markdown: kramdown
collections:
  alt:
    output: true
  text:
    output: true

theme: minima
plugins:
  - jekyll-feed
